Add shader screenshot tests (#6)
* Add shader screenshot tests
* Enable git-lfs and add gold files
* Add screenshot verification to CI. Copies much from nowinandroid.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,6 +44,32 @@ jobs:
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
 
+      - name: Run screenshot tests
+        id: verifyScreenshots
+        continue-on-error: true
+        run: ./gradlew verifyPaparazziDebug
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork
+        continue-on-error: false
+        if: steps.verifyScreenshots.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+
+      - name: Generate new screenshots if verification failed and it's a PR
+        id: recordScreenshots
+        if: steps.verifyScreenshots.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew recordPaparazziDebug
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@v5
+        if: steps.recordScreenshots.outcome == 'success'
+        with:
+          file_pattern: '*/*.png'
+          disable_globbing: true
+          commit_message: "🤖 Update screenshots"
+
       - name: Run local tests
         if: always()
         run: ./gradlew testDebug
